import "@/styles/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "updraft - web",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log(inter.className);

  return (
    <html lang="en">
      <body className={`${inter.className} p-20 m-5`}>{children}</body>
    </html>
  );
}
